# Generated by Django 5.2.8 on 2025-11-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={
                "verbose_name": "App User Profile",
                "verbose_name_plural": "App User Profiles",
            },
        ),
        migrations.AlterField(
            model_name="appuser",
            name="u_code",
            field=models.BigIntegerField(
                db_index=True,
                help_text="64-bit Unique Identifier used for BLE seed generation",
                unique=True,
            ),
        ),
    ]
