[pytest]
python_files = test_*.py *_tests.py tests.py
testpaths = api tests
addopts =
  -ra -vv --maxfail=1
  --cov=api --cov=core
  --cov-report=term-missing
  --cov-report=xml:/app/coverage/coverage.xml
  --cov-report=html:/app/coverage/htmlcov
  --junitxml=/app/coverage/junit.xml
