[pytest]
DJANGO_SETTINGS_MODULE = config.settings
pythonpath = src
# Faster test discovery
testpaths = tests
python_files = test_*.py
# Enterprise Options:
# -v: Verbose
# --reuse-db: Does not recreate the DB from scratch every time (very fast locally)
# --nomigrations: Uses the in-memory model instead of applying SQL migrations (boosts performance)
addopts = -v -p no:warnings --reuse-db --nomigrations
markers =
    unit: Fast tests that do not touch the DB or IO
    integration: Tests involving DB, API, or multiple components
