# Generated by Django 5.2.8 on 2025-11-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masterkey",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "Master Key",
                "verbose_name_plural": "Master Keys",
            },
        ),
        migrations.AlterField(
            model_name="masterkey",
            name="key_bytes",
            field=models.BinaryField(
                help_text="Raw 32-byte binary data for AES-256.", max_length=32
            ),
        ),
    ]
